Repository WildCodeSchool/orleans-0918-php-shinjuku, pull requests merged in 2018-10, with the labels that each got.

#45 Us4 s1 facebook api
  public/assets/css/main.css
  src/View/home.html.twig
  src/View/independant_sections/facebook_api.html.twig
Labels: Reviewed by PO

#40 s1 us5 final navbar
  public/assets/css/daterangepicker.css
  public/assets/css/main.css
  public/assets/css/select2.css
  public/assets/css/select2.min.css
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.eot
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.svg
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.ttf
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.woff
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.woff2
  public/assets/fonts/linearicons-v1.0.0/icon-font.min.css
  public/assets/fonts/ninjastrike/NinjaStrike.otf
  public/assets/fonts/ninjastrike/NinjaStrike.png
  public/assets/fonts/ninjastrike/license.txt
  public/assets/fonts/shojumara/OFL.txt
  public/assets/fonts/shojumara/Shojumaru-Regular.otf
  public/assets/images/banner.jpg
  public/assets/images/banner2.jpg
  public/assets/images/banner_home.jpg
  public/assets/js/daterangepicker.css
  public/assets/js/daterangepicker.js
  public/assets/js/jquery.magnific-popup.js
  public/assets/js/select2.js
  public/assets/js/select2.min.js
  public/assets/js/sweetalert.min.js
  src/View/banner_home.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/home.html.twig
  src/View/layout.html.twig
Labels: Correction Done, Reviewed by PO

#42 Footer us6 sp1
  .gitignore
  public/assets/css/main.css
  src/View/footer.html.twig
Labels: Conflict resolved, Reviewed by PO

#46 Dev
  .gitignore
  public/assets/css/daterangepicker.css
  public/assets/css/main.css
  public/assets/css/select2.css
  public/assets/css/select2.min.css
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.eot
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.svg
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.ttf
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.woff
  public/assets/fonts/linearicons-v1.0.0/WebFont/Linearicons-Free.woff2
  public/assets/fonts/linearicons-v1.0.0/icon-font.min.css
  public/assets/fonts/ninjastrike/NinjaStrike.otf
  public/assets/fonts/ninjastrike/NinjaStrike.png
  public/assets/fonts/ninjastrike/license.txt
  public/assets/fonts/shojumara/OFL.txt
  public/assets/fonts/shojumara/Shojumaru-Regular.otf
  public/assets/images/banner.jpg
  public/assets/images/banner2.jpg
  public/assets/images/banner_home.jpg
  public/assets/js/daterangepicker.css
  public/assets/js/daterangepicker.js
  public/assets/js/jquery.magnific-popup.js
  public/assets/js/select2.js
  public/assets/js/select2.min.js
  public/assets/js/sweetalert.min.js
  src/View/banner_home.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/independant_sections/facebook_api.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#64 Dev
  public/assets/css/main.css
  src/View/footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#66 Dev
  app/routing.php
  public/assets/css/api.css
  public/assets/css/main.css
  src/Controller/HomeController.php
  src/View/home.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#65 S1 us8 html about
  app/routing.php
  composer.json
  public/assets/css/main.css
  public/assets/images/about-1.jpg
  public/assets/images/about-2.jpg
  public/assets/images/about-3.jpg
  public/assets/images/hire-japanese-culture.png
  src/Controller/AboutController.php
  src/View/Home/about.html.twig
  src/View/Home/home.html.twig
  src/View/layout.html.twig
Labels: Change Requested

#80 Us 10 section article
  app/routing.php
  public/assets/css/main.css
  public/assets/images/test.jpg
  src/Controller/ArticleController.php
  src/Controller/HomeController.php
  src/Model/AbstractManager.php
  src/Model/Article.php
  src/Model/ArticleManager.php
  src/View/Home/home.html.twig
  src/View/Product/article.html.twig
  src/View/banner.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/independant_sections/facebook_api.html.twig
  src/View/layout.html.twig
  src/View/product_page.html.twig
Labels: Reviewed by PO

#83 S1 us8 html about
  .gitignore
  public/assets/css/main.css
  src/Controller/AboutController.php
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/View/Home/about.html.twig
  src/View/Home/facebook_api.html.twig
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#84 Us12 search bar
  app/routing.php
  public/assets/images/banner.jpg
  public/assets/images/banner_home.jpg
  public/assets/images/logo.png
  src/Controller/ArticleController.php
  src/Model/AbstractManager.php
  src/Model/ArticleManager.php
  src/View/Product/article.html.twig
Labels: Reviewed by PO

#81 S2 us18
  app/db.dist.php
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/main.css
  src/Controller/ContactController.php
  src/View/Article/_form.html.twig
  src/View/contact.html.twig
  src/View/contactForm.html.twig
Labels: Reviewed by PO

#85 S2 us8 add map
  public/assets/css/main.css
  src/View/Home/about.html.twig
  src/View/Home/facebook_api.html.twig
Labels: Reviewed by PO

#87 fixing rooting and css issues
  .gitignore
  app/routing.php
  public/assets/css/main.css
  src/Controller/ArticleController.php
  src/Model/ArticleManager.php
  src/View/Home/home.html.twig
  src/View/Product/article.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#88 Fixed us6 banner to merge after the "resolving problems" one
  public/assets/css/main.css
  src/View/layout.html.twig
Labels: Conflict resolved, Reviewed by PO

#86 S2 us15 product details
  app/routing.php
  public/assets/css/main.css
  src/Controller/AboutController.php
  src/Controller/ArticleController.php
  src/Model/Article.php
  src/Model/ArticleManager.php
  src/View/Article/article_details.html.twig
  src/View/Home/home.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#89 Fixed us6 height images
  public/assets/css/main.css
Labels: Reviewed by PO

#91 fixed all problems
  public/assets/css/main.css
  src/View/Home/about.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#92 Dev to master
  .gitignore
  app/db.dist.php
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/main.css
  public/assets/images/about-1.jpg
  public/assets/images/about-2.jpg
  public/assets/images/about-3.jpg
  public/assets/images/banner.jpg
  public/assets/images/banner_home.jpg
  public/assets/images/hire-japanese-culture.png
  public/assets/images/logo.png
  public/assets/images/test.jpg
  public/assets/js/uploadPreview.js
  simple-mvc.sql
  src/Controller/AboutController.php
  src/Controller/AbstractController.php
  src/Controller/ArticleController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Model/AbstractManager.php
  src/Model/Article.php
  src/Model/ArticleManager.php
  src/Model/Item.php
  src/Model/ItemManager.php
  src/View/Article/_form.html.twig
  src/View/Article/add.html.twig
  src/View/Article/article_details.html.twig
  src/View/Article/edit.html.twig
  src/View/Article/index.html.twig
  src/View/Article/show.html.twig
  src/View/Home/about.html.twig
  src/View/Home/facebook_api.html.twig
  src/View/Home/home.html.twig
  src/View/Item/_form.html.twig
  src/View/Product/article.html.twig
  src/View/banner.html.twig
  src/View/contact.html.twig
  src/View/contactForm.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/home.html.twig
  src/View/layout.html.twig
  src/View/product_page.html.twig
Labels: Reviewed by PO

#93 Article details fix
  app/routing.php
  public/assets/css/main.css
  public/assets/images/icons/logo_certified.png
  src/Controller/ArticleController.php
  src/Model/ArticleManager.php
  src/View/Article/article_details.html.twig
Labels: Reviewed by PO

#95 fix css contact, preview picture, changement de chemin dans le champ picture
  public/assets/css/main.css
  public/assets/js/uploadPreview.js
  src/Controller/ArticleController.php
Labels: Conflict resolved, Reviewed by PO

#130 fix s2_us15_Product_Details
  src/View/Product/article.html.twig
Labels: Reviewed by PO

#128 Fixed css searchbar us 10
  public/assets/css/main.css
  src/View/Article/article.html.twig
  src/View/Article/article_page_search.html.twig
  src/View/product_page.html.twig
Labels: Reviewed by PO

#131 Fix labels admin page & routing /home
  app/routing.php
  src/View/Article/_form.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#133 S3 us23 admin articles
  app/routing.php
  src/Controller/ArticleController.php
  src/View/Article/list.html.twig
Labels: Correction Done, Reviewed by PO

#134 fix searchbar + changing category path
  src/Controller/ArticleController.php
  src/View/Article/list.html.twig
Labels: Reviewed by PO

#106 Us2 sp2 acc highlight
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/main.css
  src/Controller/HomeController.php
  src/Model/AbstractManager.php
  src/Model/ArticleManager.php
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#135 fix padding, font, css
  public/assets/css/main.css
  src/View/Home/about.html.twig
Labels: Reviewed by PO

#136 update home link in 'Nos Nouveautés'
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#132 us17 v1 finished
  public/assets/css/main.css
  src/Controller/ArticleController.php
  src/Model/ArticleManager.php
  src/View/Article/article.html.twig
Labels: Conflict resolved, Reviewed by PO

#138 Fix-swiftmailer
  src/Controller/ContactController.php
Labels: Reviewed by PO

#141 fixing css
  public/assets/css/main.css
Labels: Reviewed by PO

#139 Us22 sp3 admin delete button
  app/routing.php
  src/Controller/ArticleController.php
  src/Model/ArticleManager.php
  src/View/Article/list.html.twig
  src/View/Home/home.html.twig
Labels: Conflict resolved

#140 fixing category links
  src/Controller/ArticleController.php
  src/View/Article/article.html.twig
Labels: Correction Done, Reviewed by PO

#143 buttons created + links done
  public/assets/css/main.css
  src/View/Article/list.html.twig
Labels: Correction Done, Reviewed by PO

#146 images link works
  src/View/Article/article.html.twig
  src/View/Article/article_details.html.twig
Labels: Reviewed by PO

#150 placeholder for articles without picture
  public/assets/images/manga.png
  src/View/Article/article.html.twig
  src/View/Article/article_details.html.twig
Labels: Reviewed by PO

#98 Us25 sp3 searchbar
  app/routing.php
  public/assets/css/main.css
  src/Controller/ArticleController.php
  src/Model/ArticleManager.php
  src/View/Article/article.html.twig
  src/View/Article/article_page_search.html.twig
  src/View/Article/cardArticle.html.twig
  src/View/Article/pagination.html.twig
  src/View/header.html.twig
Labels: Conflict resolved, Reviewed by PO

#151 Fix style article details
  public/assets/css/main.css
  src/View/Article/article_details.html.twig
Labels: Conflict resolved
