Repository WildCodeSchool/orleans-0918-php-shinjuku, pull requests merged in 2018-11, with the labels that each got.

#154 Dev
  app/routing.php
  composer.json
  composer.lock
  public/assets/css/main.css
  public/assets/images/icons/logo_certified.png
  public/assets/images/manga.png
  public/assets/js/uploadPreview.js
  src/Controller/ArticleController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Model/AbstractManager.php
  src/Model/ArticleManager.php
  src/View/Article/_form.html.twig
  src/View/Article/article.html.twig
  src/View/Article/article_details.html.twig
  src/View/Article/cardArticle.html.twig
  src/View/Article/list.html.twig
  src/View/Article/pagination.html.twig
  src/View/Home/about.html.twig
  src/View/Home/home.html.twig
  src/View/header.html.twig
  src/View/product_page.html.twig
Labels: Reviewed by PO

#137 Fix delete preview
  public/assets/css/main.css
  public/assets/js/uploadPreview.js
  src/Controller/ArticleController.php
  src/View/Article/_form.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#152 images max height
  public/assets/css/main.css
  src/View/Article/article_details.html.twig
  src/View/Article/list.html.twig
  src/View/Home/home.html.twig
  src/View/banner_home.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#160 Admin routing update
  app/routing.php
  src/Controller/ArticleController.php
  src/View/Article/article_details.html.twig
  src/View/Article/list.html.twig
Labels: Reviewed by PO

#161 deleting an useless div broking the view
  src/View/Article/article_details.html.twig
Labels: Reviewed by PO

#158 Fix css
  public/assets/css/main.css
  src/View/Article/article_details.html.twig
  src/View/Article/cardArticle.html.twig
  src/View/Article/list.html.twig
  src/View/Home/home.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#159 fix css et html
  public/assets/css/main.css
  public/assets/css/styles.css
  public/assets/images/background.png
  public/assets/images/banner.jpg
  src/View/Home/facebook_api.html.twig
  src/View/Home/home.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#162 fix du css de la page add et page edit
  public/assets/css/main.css
  src/Controller/ArticleController.php
  src/View/Article/_form.html.twig
Labels: Reviewed by PO

#163 size of 'Description :' in article details reducted
  public/assets/css/main.css
Labels: Reviewed by PO

#165 scrolling right and fixed pages
  public/assets/css/api.css
  public/assets/css/main.css
  public/assets/css/styles.css
  src/View/Article/add.html.twig
  src/View/Article/article_details.html.twig
  src/View/Article/edit.html.twig
  src/View/Article/list.html.twig
  src/View/Home/about.html.twig
  src/View/Home/home.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#166 add link is OK
  src/View/Article/list.html.twig
Labels: Reviewed by PO

#167 condition for defaut image if not set
  src/View/Article/cardArticle.html.twig
  src/View/Article/list.html.twig
Labels: Reviewed by PO

#168 fix fontsize adresse horaire tel
  public/assets/css/main.css
  src/View/Home/about.html.twig
Labels: Reviewed by PO

#169 Fix pagination
  src/View/Article/pagination.html.twig
Labels: Reviewed by PO

#171 ajout block title sur toute les pages
  src/View/Article/add.html.twig
  src/View/Article/article.html.twig
  src/View/Article/article_details.html.twig
  src/View/Article/edit.html.twig
  src/View/Article/index.html.twig
  src/View/Article/list.html.twig
  src/View/Article/show.html.twig
Labels: Reviewed by PO

#170 Fix banner
  src/View/layout.html.twig
Labels: Conflict resolved

#172 Dev
  app/routing.php
  public/assets/css/api.css
  public/assets/css/main.css
  public/assets/css/styles.css
  public/assets/images/background.png
  public/assets/images/banner.jpg
  public/assets/js/uploadPreview.js
  src/Controller/ArticleController.php
  src/Model/ArticleManager.php
  src/View/Article/_form.html.twig
  src/View/Article/add.html.twig
  src/View/Article/article.html.twig
  src/View/Article/article_details.html.twig
  src/View/Article/cardArticle.html.twig
  src/View/Article/edit.html.twig
  src/View/Article/index.html.twig
  src/View/Article/list.html.twig
  src/View/Article/pagination.html.twig
  src/View/Article/show.html.twig
  src/View/Home/about.html.twig
  src/View/Home/facebook_api.html.twig
  src/View/Home/home.html.twig
  src/View/banner_home.html.twig
  src/View/footer.html.twig
  src/View/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by PO

#173 fix_empty_result
  src/View/Article/cardArticle.html.twig
Labels: Reviewed by PO

#176 PSR correction on ContactController and ArticleController
  src/Controller/ArticleController.php
  src/Controller/ContactController.php
Labels: Reviewed by PO

#178 PSR fix on AbstractManager
  src/Model/AbstractManager.php
Labels: Reviewed by PO

#175 finish and work
  public/assets/css/main.css
  public/assets/css/styles.css
  public/assets/images/banner-admin.jpg
  public/assets/images/banner-contact.jpg
  src/Controller/AboutController.php
  src/Controller/ArticleController.php
  src/Controller/ContactController.php
  src/View/Article/article.html.twig
  src/View/Article/cardArticle.html.twig
  src/View/Article/list.html.twig
  src/View/Home/home.html.twig
  src/View/contact.html.twig
  src/View/header.html.twig
Labels: Conflict resolved, Reviewed by PO

#177 PSR fix on ArticleManager and Article.php
  src/Model/Article.php
  src/Model/ArticleManager.php
Labels: Correction Done

#179 last PSR fix
  src/Controller/AboutController.php
Labels: Reviewed by PO

#181 final change
  public/assets/css/main.css
  src/View/Article/add.html.twig
  src/View/Article/cardArticle.html.twig
  src/View/Article/edit.html.twig
  src/View/Article/list.html.twig
Labels: Reviewed by PO

#182 update css for image in article details
  public/assets/css/main.css
  src/View/Article/article_details.html.twig
Labels: Reviewed by PO

#183 Fix mobile version
  public/assets/css/main.css
  public/assets/css/styles.css
  src/View/Article/article.html.twig
  src/View/Home/about.html.twig
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#185 modif bouton valider page admin
  public/assets/css/main.css
  src/View/Article/_form.html.twig
Labels: Reviewed by PO

#184 TO DO AFTER FIX_MOBILE_VERSION
  public/assets/css/main.css
  public/assets/css/styles.css
  public/assets/images/banner-admin.jpg
  public/assets/images/banner-contact.jpg
  src/Controller/AboutController.php
  src/Controller/ArticleController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Model/AbstractManager.php
  src/Model/Article.php
  src/Model/ArticleManager.php
  src/View/Article/_form.html.twig
  src/View/Article/add.html.twig
  src/View/Article/article.html.twig
  src/View/Article/article_details.html.twig
  src/View/Article/cardArticle.html.twig
  src/View/Article/edit.html.twig
  src/View/Article/list.html.twig
  src/View/Home/about.html.twig
  src/View/Home/home.html.twig
  src/View/contact.html.twig
  src/View/header.html.twig
Labels: Reviewed by PO

#186 Utlime fix
  public/assets/css/main.css
  src/View/Article/article.html.twig
  src/View/Article/article_details.html.twig
  src/View/Home/home.html.twig
Labels: Correction Done, Reviewed by PO

#187 Dev
  public/assets/css/main.css
  src/View/Article/article.html.twig
  src/View/Article/article_details.html.twig
  src/View/Home/home.html.twig
Labels: Reviewed by PO

#189 Fix empty result2
  src/View/Article/cardArticle.html.twig
Labels: Reviewed by PO

#190 delete of the navbar around the searchbar
  src/View/Article/article.html.twig
  src/View/footer.html.twig
Labels: Reviewed by PO

#191 fix_footer
  src/View/footer.html.twig
Labels: Reviewed by PO

#192 contact link
  src/View/footer.html.twig
Labels: Conflict

#193 correction all titre
  src/View/Article/add.html.twig
  src/View/Article/edit.html.twig
  src/View/contactForm.html.twig
Labels: Reviewed by PO

#194 Dev to master à accepter après les autres PR
  public/assets/css/styles.css
  src/View/Article/add.html.twig
  src/View/Article/article.html.twig
  src/View/Article/cardArticle.html.twig
  src/View/Article/edit.html.twig
  src/View/contactForm.html.twig
  src/View/footer.html.twig
Labels: Reviewed by PO
